# This is a basic workflow to help you get started with Actions

name: Scan k8s YAML using KubeLinter

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Scan yaml using KubeLinter
        uses: stackrox/kube-linter-action@v1
        with:
          directory: k8s-yaml-sample/
          # config: .kube-linter/config.yaml
        continue-on-error: true
        
      - name: Scan Helm charts using KubeLinter
        uses: stackrox/kube-linter-action@v1
        with:
          directory: helm-chart-sample/
          # config: .kube-linter/config.yaml
        continue-on-error: true
          
